### ISSUE TITLE
encoder_tb

### ISSUE THREAD

**Issue by foez-ahmed** [DSi-DV/rv64g-core#12]
Testbench Needed

**Comment by foez-ahmed** [comment]
@tahmeedKENJI did you create the MR?

**Comment by foez-ahmed** [comment]
I see you've put your changes in fixed-priority-arb branch. Try not to mix things in future.

I'm fixing the case for the time being

**Comment by tahmeedKENJI** [comment]
I am extremely sorry vaiya. I should have mentioned it when the branches
were being merged. I am glad to hear everything is ok, but I am extremely
sorry for the inconveniences. It will not happen again.
