### ISSUE TITLE
reg_grt_ckr

### ISSUE THREAD

**Issue by foez-ahmed** [DSi-DV/rv64g-core#29]

**Comment by foez-ahmed** [comment]
Start with these IOs
```SV
```

**Comment by foez-ahmed** [comment]
Missed out a pin and seems like a whole array of jumps has been added. These is the updates IOs:
```SV
module reg_gnt_ckr #(
    localparam int NR = rv64g_pkg::NUM_REGS
) (
    input  logic pl_valid_i,
    output logic pl_ready_o,

    input  logic          jump_i,
    input  logic [NR-1:0] reg_req_i,

    input  logic [NR-1:0] locks_i,
    output logic [NR-1:0] locks_o,

    output logic arb_req_o,
    input  logic arb_gnt_i
);
```

**Comment by SubhanBihan** [comment]
Bhai, do I need to make design or documentation for this or what? It's not clear

**Comment by foez-ahmed** [comment]
Well this is the real life challenge. Let me know when we can discuss

**Comment by SubhanBihan** [comment]
> Well this is the real life challenge. Let me know when we can discuss

I guess we can discuss in today;s sync-up meeting

**Comment by foez-ahmed** [comment]
If the case is not jump, then rd=0 can't be locked under no condition.

If there is no valid, locks_o = lock_i

**Comment by SubhanBihan** [comment]
If there's no valid, should arb_req_o be 0 or x?

**Comment by foez-ahmed** [comment]
What's you expectation?

**Comment by SubhanBihan** [comment]
Bhai, I fixed the logic (was pretty simple, should've thought of it sooner - but this gave me insight into why not to use comparators in RTL unless absolutely necessary). But the PR isn't passing to a doc mismatch (strange since I fixed the port defs in the .md file)
