### ISSUE TITLE
decoder performance improvement

### ISSUE THREAD

**Issue by foez-ahmed** [DSi-DV/rv64g-core#57]
instruction decoder provides an encoded func that again needs to be decoded at execution level blocks. Seemingly the faster performance can be achieved by dropping out the func encoded and decoding, and instead passing one hot func

**Comment by tahmeedKENJI** [comment]
RTL needs revision. seems like it can't distinguish if a code is valid or not. cmd_o is supposed to be one-hot encoded but there are a few cases where that is not the case. SYNC-UP IMMEDIATE.

**Comment by foez-ahmed** [comment]
I see. Sure
