### ISSUE TITLE
fixed_priority_arbiter_tb

### ISSUE THREAD

**Issue by foez-ahmed** [DSi-DV/rv64g-core#9]
Testbench Needed

**Comment by tahmeedKENJI** [comment]
Creating a branch and working on the issue. Permission to proceed?

**Comment by tahmeedKENJI** [comment]
Something is wrong with the fixed priority arbiter RTL. Requires discussion.

**Comment by foez-ahmed** [comment]
Let me know a suitable time for discussion

**Comment by foez-ahmed** [comment]
`allow_i` pin was missing earlier. I've just added it. Please account for that in TB as well

**Comment by foez-ahmed** [comment]
I don't see the priority mentioned anywhere in comment or doc.
req_i [0] should have the highest priority. I'll update the docs soon
